title: waratuman
author: James R. Bracy
permalink: none
paginate: 1
auto: true
server: true
server_port: 3000
markdown: rdiscount
paginate: 1
permalink: /:year/:month/:day/:title
safe: true
lsi: false
pygments: true